### ISSUE TITLE
Wrong length constraints?

### ISSUE THREAD

**Issue by sashulyak** [pruiz/AberrantSMPP#4]
Hello!

In **SmppBind** class you have lenght constraints for **SystemID** and **Password**. But different SMS services allows you to set any length for password and user name.

I spent 2 days trying to understand why I cannot connect to my SMS gateway. The reason was that my password is longer than 8 symbols.

Maybe you should refuse from these constraints? What do you think?

Thank you!

**Comment by pruiz** [comment]
Hi,

The length of those fields are taken from the Smpp (v5.0) spec, which you can find here: http://opensmpp.org/specs/smppv50.pdf

As they are limited in lenght by the spec, I am not really sure wether this library should support longer values. But I will try to review the impact of the change, just in case.
