### ISSUE TITLE
OnSubmitSmResp event not working

### ISSUE THREAD

**Issue by Andy5000** [pruiz/AberrantSMPP#8]
If the message is not segmented. SendPdu (msg); all Ok
If a message is segmented. Send (msg, SmppSarMethod. UseSmppSegmentation);
I don't get a OnSubmitSm event, OnSubmitSmResp...

SMPPCommunicator.cs
private void ProcessPduQueue(object queueStateObj)
{
...
if (_RequestsAwaitingResponse.ContainsKey(packet.SequenceNumber))
	{
        ...
	state.EventHandler.Set();
           <--  Here, too, must be handled events FireEvents(packet) ?
	continue;
	}
}

// based on each Pdu, fire off an event
FireEvents(packet);  <---     Not works always

**Comment by pruiz** [comment]
Hi,

I am sorry, but I do not fully understand your question/suggestion.

May you re-open this issue with a sample code, test, or something reproducing the issue?
